apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-flaskapp-deployment
  labels:
    app: kc-flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kc-flaskapp
  template:
    metadata:
      labels:
        app: kc-flaskapp
    spec:
      containers:
      - name: kc-flaskapp
        image: kinnar0112/kc-flaskapp-k8s:1.0
        ports:
        - containerPort: 5000
