apiVersion: v1
kind: Service
metadata:
  name: kc-flaskapp-service
spec:
  selector:
    app: kc-flaskapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005